# Splitting the dataset into training and testing datasets

In [1]:
import numpy as np

In [5]:
#old: from sklearn.cross_validation import train_test_split

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
x,y = np.arange(10).reshape((5,2)), range(5)

In [7]:
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
list(y)

[0, 1, 2, 3, 4]

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)

In [14]:
x_train

array([[6, 7],
       [4, 5],
       [0, 1]])

In [15]:
y_train

[3, 2, 0]

In [16]:
x_test

array([[2, 3],
       [8, 9]])

In [17]:
y_test

[1, 4]