In [2]:
list = [1,2,3]

In [1]:
import numpy as np

In [5]:
arr = np.array(list)

In [6]:
arr

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
# 3d array
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [20]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [21]:
# generate a vector of equally 10 distatn points
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### identity matrix

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.48550438, 0.92930314, 0.65653867, 0.87369291, 0.92561103])

In [25]:
np.random.rand(5,5)

array([[0.44208672, 0.37730419, 0.60147763, 0.24625398, 0.24653736],
       [0.18122847, 0.11700222, 0.17134524, 0.69835023, 0.49647686],
       [0.11903627, 0.90124783, 0.50761682, 0.3547311 , 0.13480881],
       [0.1265838 , 0.9666939 , 0.51144747, 0.30223198, 0.85650899],
       [0.03500486, 0.01343336, 0.60583855, 0.81565069, 0.77599861]])

In [26]:
# to get a random vector from a gaussian distribution(normal distribution)
np.random.randn(6)

array([ 0.26772915, -0.42289623, -0.39695382,  0.14770922, -1.32544207,
       -1.42852202])

In [33]:
np.random.randint(1,100,5)

array([99, 92, 67, 71, 20])

In [34]:
np.random.randint(1,5)

3

In [35]:
arr = np.arange(25)

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(1,50,10)

In [40]:
ranarr

array([34, 34, 32, 17, 30, 14, 13, 10, 45, 31])

In [41]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
ranarr.max()

45

In [43]:
ranarr.min()

10

In [44]:
ranarr.mean()

26.0

In [45]:
# return index of the max value
ranarr.argmax()

8

In [46]:
ranarr.argmin()

7

In [48]:
arr.shape

(25,)

In [49]:
ranarr.shape

(10,)

In [50]:
arr.reshape(5,5).shape

(5, 5)

In [51]:
arr.dtype

dtype('int32')

### idexing

In [53]:
arr = np.arange(0,11)

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [55]:
arr[8]

8

In [56]:
arr[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [57]:
arr_copy = arr

In [58]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**note** if we create an other variable and affect the values of our numpy array in it, by changing the values of the new varible, the values of the original array will be alterd also! so we use the method copy to avoid that kind of behaviour!

In [59]:
arr_copy[2] = 100

In [60]:
arr

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [61]:
arr_new = arr[0:6].copy()

In [62]:
arr_new

array([  0,   1, 100,   3,   4,   5])

In [63]:
arr_new[2] = 66

In [64]:
arr_new

array([ 0,  1, 66,  3,  4,  5])

In [65]:
arr

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10])

# Matrix indexing

In [66]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [67]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[1][1]

25

In [69]:
arr_2d[1]

array([20, 25, 30])

In [70]:
arr_2d[1,1]

25

In [71]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [75]:
arr = np.arange(1,11)

In [76]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [78]:
bool_arr = arr < 5

In [79]:
bool_arr

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [80]:
arr[bool_arr]

array([1, 2, 3, 4])

In [81]:
arr[arr < 5]

array([1, 2, 3, 4])

### Opertators

arr + arr, arr-arr, arr*arr, arr+2, arr/2.....

In [84]:
arr1 = np.ones((5,1))

In [85]:
arr2 = np.ones((1,5))

In [86]:
arr1*arr2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Exercices

Create a 3x3 matrix with values ranging from 0 to 8

In [88]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [89]:
arr1.sum()

5.0

In [90]:
arr1.std()

0.0

In [94]:
arr1.sum(axis=0)

array([5.])

In [95]:
arr1.sum(axis=1)

array([1., 1., 1., 1., 1.])